/*-- Auto Generated By Alice --*/
using System.Collections.Generic;
/*-- Auto Generated By Alice --*/
using System.Linq;
using System;
using System.IO;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
namespace ConsoleApp6
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int s = int.Parse(Console.ReadLine());
            Console.WriteLine((s%2==0)? "Paros" : "Paratlan");
        }
    }
}
